version: "2"
services:
  node:
    image: node:8
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes_from:
      - nodedata
    working_dir: /opt/publica_mvp
    tty: true

  blockchain:
    build: ./blockchain
    expose:
      - "8545"
    ports:
      - "8545:8545"
    volumes_from:
      - blockchaindata
    working_dir: /opt/blockchain
    tty: true

  nodedata:
    image: tianon/true
    volumes:
      - ./node:/opt/publica_mvp

  blockchaindata:
    image: tianon/true
    volumes:
      - ./blockchain:/opt/blockchain
