module.exports = {
    extends: ['airbnb-base', 'plugin:vue/essential'],
    plugins: ['vue'],
    parserOptions: {
        "ecmaVersion": 2017
    },
    rules: {
        'indent': [1, 4, { 'SwitchCase': 1 } ],
        'class-methods-use-this': 0,
        'camelcase': 0,
        'no-return-await': 0,
        'semi': 0,
        'prefer-rest-params': 0,
        'no-plusplus': 0,
        'extensions': 0,
        'import/extensions': 0,
        'comma-dangle': 0,
        'object-shorthand': 2,
        'space-before-function-paren': [1, 'never'],
        'import/no-extraneous-dependencies': 0,
        'no-param-reassign': 0,
        'no-restricted-globals': 0,
        'no-return-assign': 0,
        'no-mixed-operators': 0,
        'no-throw-literal': 0,
        'no-undef': 0,
        'func-names': 0,
        'no-unused-vars': 0,
        'no-underscore-dangle': 0,
        'quote-props': 0,
        'no-console': [1, { 'allow': ['error', 'warn'] } ],
        'new-cap': 0,
        'no-new': 0,
        'import/no-named-as-default-member': 0,
        'import/no-named-as-default': 0,
        'no-shadow': 0,
        'no-shadow-restricted-names': 0,
        'one-var': 0,
        'no-loop-func': 0,
        'no-alert': 0,
        'no-mutable-exports': 0,
        'import/no-mutable-exports': 0,
        'no-restricted-syntax': 1,
        'no-control-regex': 0,
        'no-extra-bind': 0,
        'yoda': 0,
        'no-cond-assign': 0,
        'no-extra-semi': 0,
        'default-case': 0,
        'wrap-iife': 0,
        'no-reserved-keys': 0,
        'import/no-unresolved': 0,
        'prefer-template': 1,
        'no-use-before-define': 1,
        'no-var': 1,
        'vue/valid-template-root': 0,
        'import/newline-after-import': 0,
        'prefer-arrow-callback': ['error', { 'allowUnboundThis': false }],
        'consistent-return': 0,
        'max-len': 0,
        'radix': 0,
        'vars-on-top': 1,
        'array-callback-return': 0,
        'no-else-return': 1,
        'no-confusing-arrow': 0,
    }
}
